// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: provisioner.proto

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CluserServiceClient is the client API for CluserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CluserServiceClient interface {
}

type cluserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCluserServiceClient(cc grpc.ClientConnInterface) CluserServiceClient {
	return &cluserServiceClient{cc}
}

// CluserServiceServer is the server API for CluserService service.
// All implementations should embed UnimplementedCluserServiceServer
// for forward compatibility
type CluserServiceServer interface {
}

// UnimplementedCluserServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCluserServiceServer struct {
}

// UnsafeCluserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CluserServiceServer will
// result in compilation errors.
type UnsafeCluserServiceServer interface {
	mustEmbedUnimplementedCluserServiceServer()
}

func RegisterCluserServiceServer(s grpc.ServiceRegistrar, srv CluserServiceServer) {
	s.RegisterService(&CluserService_ServiceDesc, srv)
}

// CluserService_ServiceDesc is the grpc.ServiceDesc for CluserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CluserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provisioner.CluserService",
	HandlerType: (*CluserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "provisioner.proto",
}
